export enum EnvVars {
  ENV_LAZY_LOAD = 'ENV_LAZY_LOAD',
  PORT = 'PORT',
  HOST = 'HOST',
  NODE_ENV = 'NODE_ENV',
  APP_NAME = 'APP_NAME',
  API_VERSION = 'API_VERSION',
  APP_URL = 'APP_URL',
  SERVER_PREFIX = 'SERVER_PREFIX',
  FE_URL = 'FE_URL',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
}
export enum WinstonEnvs {
  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLE_LIMIT = 'THROTTLE_LIMIT',
  LOG_MAX_SIZE = 'LOG_MAX_SIZE',
  LOG_MAX_DATE = 'LOG_MAX_DATE',
}

export enum GoogleEnvs {
  GOOGLE_OAUTH2_CLIENT_ID = 'GOOGLE_OAUTH2_CLIENT_ID',
  GOOGLE_OAUTH2_CLIENT_SECRET = 'GOOGLE_OAUTH2_CLIENT_SECRET',
}

export enum MailEnvs {
  MAIL_INCOMING_USER = 'MAIL_INCOMING_USER',
  MAIL_INCOMING_PASS = 'MAIL_INCOMING_PASS',
  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
}

export enum GithubEnvs {
  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
}

export enum FacebookEnvs {
  FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID',
  FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET',
}
