version: ${VERSION}

services:
  pg_master_sso:
    container_name: pg_master_sso
    build:
      context: .
    volumes:
      - ${PATH_BACKUP_DATA}/pg_master_sso:/var/lib/postgresql/data
    environment:
      - POSTGRES_MASTER=true
    ports:
      - ${PG_MASTER_PORT}:5432
  # pg2:
  #   container_name: pg2
  #   build:
  #     context: .
  #     args:
  #       - POSTGRES_MASTER_HOST=${PG_MASTER_HOST}
  #       - POSTGRES_MASTER_PORT=${PG_MASTER_PORT}
  #   environment:
  #     -  POSTGRES_SLAVE=true
  #   volumes:
  #     - ${PATH_BACKUP_DATA}/pg2:/var/lib/postgresql/data
  #     # - ./init_db_secondary.sql:/docker-entrypoint-initdb.d/init.sql
  #   depends_on:
  #     - ${PG_MASTER_HOST}
  #   ports:
  #     - 5433:5432

  # pg3:
  #   container_name: pg3
  #   build:
  #     context: .
  #     args:
  #       - POSTGRES_MASTER_HOST=${PG_MASTER_HOST}
  #       - POSTGRES_MASTER_PORT=${PG_MASTER_PORT}
  #   environment:
  #     -  POSTGRES_SLAVE=true
  #   volumes:
  #     - ${PATH_BACKUP_DATA}/pg3:/var/lib/postgresql/data
  #     # - ./init_db_secondary.sql:/docker-entrypoint-initdb.d/init.sql
  #   depends_on:
  #     - ${PG_MASTER_HOST}
  #   ports:
  #     - 5434:5432
